spring:
 datasource:
  url: jdbc:mysql://localhost:3306/pets_palette_db
  username: root
  password: loona

 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
  hibernate:
   ddl-auto: update
